### ISSUE TITLE
game logic

### ISSUE THREAD

**Issue by jesskeepswimming** [ncheungg/yeetcode-backend#2]
Backend:
- random problem generator 
- Websocket logic
-- keep state of player conditions send out problem when both readys recieved
--- add types: 
Ready = 'ready',
Waiting = 'waiting',
Playing = 'playing',
Spectating = 'spectating',

**Comment by ncheungg** [comment]
done in #3 (kinda)

**Comment by ncheungg** [comment]
should be done in #3 #4 and #6
